### ISSUE TITLE
Chunkloads in other dims get disabled randomly

### ISSUE THREAD

**Issue by teufler80** [ModdedMinecraftClub/issue-tracker#147]
Just recently happened after a crash, and happenes from day to day for no reason at all.
Since people have setups in other dims, this sometimes breaks stuff.

**Comment by ThePixelbrain** [comment]
The issue is likely caused by this NPE, which I have fixed on my branch of FTB Utilities. https://github.com/FTBTeam/FTB-Utilities/pull/1159

I believe we run the default version of FTB Utilities on E2E. I will take care of this and exchange the jar with my fork. Will let you know when I did the change.

**Comment by teufler80** [comment]
That sounds awsome, ty

**Comment by ThePixelbrain** [comment]
The issue should be fixed now. Please confirm it actually is, so I can close the ticket.

**Comment by ThePixelbrain** [comment]
Actually, the issue will only be fixed after the next server restart. Please check after the next restart and confirm.

**Comment by teufler80** [comment]
Yeah ill monitor the behavior for a day, then close the ticket if thats fine.
Because i cant really replicate the issue

**Comment by teufler80** [comment]
Well seems to work, i goona close it, thanks
