### ISSUE TITLE
Chunks occasionally seem to rollback once unloaded

### ISSUE THREAD

**Issue by Rocraft** [ModdedMinecraftClub/issue-tracker#164]
My base is sort of split between 2 areas, where each is just out of range to load the other.
Multiple times, chunks have seemed to rollback once I leave one area for the other, so I'll move a bunch of machines, leave, and once I return they've all returned to their original positions.
This has deleted some stacks of items I've fed my machines, as well as parts of multi's that I've been building in pieces. It has also similarly duplicated some blocks/items

Originally I just thought I was just going insane, but with an actual dupe of my nanochestplate something is definitely going on.
My best guess is that it has something to do with loading/unloading the chunks and them not saving. I've tried chunkloading them for a bit, and nothing happened, but it wasn't a consistent thing in the first place, so I'm not sure whats going on.

**Comment by Rocraft** [comment]
Just relogged to have my base roll back a few hours.

**Comment by dseakle** [comment]
I have run into this issue today (9/8/24) as well. I created a thaumium wand core, the gold caps deposited them along with an essentia provider in a chest, left for the TF to get Lich bones and then came back to all recently placed items missing from the chest and the pieces of the gold caps in the arcane crafting table. I seem to have irretrievably lost the wand core and essentia provider.

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket. If any item replacements are required feel free to reach out to one of us and reference this issue and we'll be happy to replace any lost items we possibly can.

Thank you!
