### ISSUE TITLE
Lost machines due to rain bug

### ISSUE THREAD

**Issue by Emiralp26** [ModdedMinecraftClub/issue-tracker#79]
I lost 3 LV Macerators and a forge hammer due to a rain bug. It has rained before, and never have these machines exploded. I believe the machines exploded because I joined while there was rain. This is not the first time happening. 

https://youtu.be/fkJBzt9lSj4

There is also a weird amount of pollution which never happened before.

I am unaware if this is an intended feature or if it is an bug

**Comment by Duckgrass** [comment]
You need to cover those machines much more since it's not just the block above the machine that gets checked IIRC.
The pollution from machines overloading is an intended mechanic.
If you feel like it, we can refund your machines. At me (Duckhemp/Duckweed) or staff in the discord when you get online next if you want a refund.
